# Taken from Bret Fisher's "node-docker-good-defaults" project
# https://github.com/BretFisher/node-docker-good-defaults/blob/master/docker-compose.yml

version: '3.1'

services:
  mysql:
    build: ./db
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
        test: "exit 0"

  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
    # NOTE: if nodemon isn't restarting on changes, you might be on Windows
    # which has trouble seeing file changes, so add -L to use legacy polling
    # https://github.com/remy/nodemon#application-isnt-restarting
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229
    ports:
      - "3000:3000" # Changed for Upcoming docs
      - "5858:5858"
      - "9229:9229"
    volumes:
      - .:/opt/app
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location. Thanks to PR from @brnluiz
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql

volumes:
    notused: